plugins:
  - jekyll-remote-theme
remote_theme: "jekyll/minima@1e8a445"

title: Methodology Assignment 4
baseurl: '/' # the subpath of your site, e.g. /blog
url: 'https://waleung1231.github.io/DSC180A-Methodology-4' # the base hostname & protocol for your site, e.g. http://example.com
author: Suraj Rampure
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]